securewallet/bc_implementation/views.py
import json

from flask_login import current_user,login_required
from securewallet import db
from securewallet.models import WalletAccount
from securewallet.generate_wallet.forms import GenerateWalletForm
from securewallet.generate_wallet.wallets import *
from securewallet.bc_implementation.forms import AddNodeForm,BlockForm
from securewallet.models import AddNode,Block
from securewallet.bc_implementation.blockchain import Blockchain,Block

from flask import render_template
from flask import render_template, url_for, flash, redirect, request, Blueprint, session, Response

blockchain=Blockchain()
#block=Block()


bc_implementation = Blueprint('bc_implementation', __name__)


@bc_implementation.route('/blockchain/main')
def main_blockchain():
    return render_template('./main_blockchain.html')



@bc_implementation.route('/configure')
def get_chain():
    chain_data = []
    for block in blockchain.chain:
        chain_data.append(block.__dict__)
    return json.dumps({"length": len(chain_data),
                       "chain": chain_data})


@bc_implementation.route('/transactions/get', methods=['GET'])
def get_transactions():
    # Get transactions from transactions pool
    transactions = blockchain.current_transactions
    return transactions

@bc_implementation.route(('/transactions/mine'), methods=['GET'])
def mine_transactions():
    form = BlockForm()

    last_block = blockchain.chain[-1]
    #nonce = blockchain.proof_of_work()


    mined_block = BlockForm(index=form.block_index,
                            transaction=form.transactions.data,
                            timestamp=form.date.data,
                            previous_hash=form.previous_hash.data)

    flash('New Block Forged', category='success')

    db.session.commit()

    return render_template('mine_transactions.html',mined_block=mined_block,form=form)


@bc_implementation.route('/node/add', methods=['GET','POST', ])
def add_nodes():
    """add a node."""

    form = AddNodeForm()

    if form.validate_on_submit():
        nodes = AddNode.query.filter_by(nodes_url=form.nodes_url.data).first()

        if nodes is not None:
            flash('This node already exists, Please enter a different url.', category='error')
            return redirect(url_for('bc_implementation.add_nodes'))

        nodes = AddNode(nodes_url=form.nodes_url.data)
        db.session.add(nodes)
        db.session.commit()
        flash('Thanks for registering! Now you can mine transactions!', category='success')
        return redirect(url_for('bc_implementation.add_nodes'))

    return render_template('add_node.html', form=form)

securewallet/core/views.py
from flask import render_template, Blueprint, request,url_for, redirect
import joblib
import pandas as pd
from securewallet.core.forms import FeatureSelectionForm
from securewallet import db
from securewallet.models import BWAIRanking

core = Blueprint('core', __name__)

# Load the Random Forest model
model = joblib.load('random_forest_model.pkl')
DATA_FILE = 'test_dataset.csv'
def normalize_data():
    # Load data from CSV file
    df = pd.read_csv(DATA_FILE)

    # Convert 'No' to 0 and 'Yes' to 1 for specified columns
    binary_choice_columns = [
        'Support TOTP', 'Support Facial Recognition', 'Multiple Cryptocurrencies',
        'Non-Custodial', 'Custodial'
    ]
    for column in binary_choice_columns:
        if column in df.columns:
            df[column] = df[column].map({'No': 0, 'Yes': 1}).astype(int)
        else:
            print(f"Column {column} not found in the dataset.")

    # Normalize specified numerical columns
    numerical_columns = ['Wallet Age', 'Rating', 'Security Level']
    for column in numerical_columns:
        if column in df.columns:
            df[column] = (
                    (df[column] - df[column].min()) /
                    (df[column].max() - df[column].min())
            )
        else:
            print(f"Column {column} not found in the dataset.")

    return df


@core.route('/')
def index():
    return render_template('index.html')

@core.route('/ranking', methods=['GET', 'POST'])
def ranking():
    form = FeatureSelectionForm()
    if request.method == 'POST' and form.validate_on_submit():
        df = normalize_data()

        # Step 2: Generate predictions for all wallets
        predictions = model.predict(df)

        # Step 3: Update each wallet's rankings in the database
        for i, wallet_predictions in enumerate(predictions):

            wallet_identifier = df.iloc[i]['Wallet Identifier']
            wallet = BWAIRanking.query.filter_by(identifier=wallet_identifier).first()

            if wallet:
                wallet.update_rankings(
                    ranking=wallet_predictions[0],
                    totp_ranking=wallet_predictions[1],
                    facial_recognition_ranking=wallet_predictions[2],
                    cryptocurrencies_ranking=wallet_predictions[3],
                    age_ranking=wallet_predictions[4],
                    non_custodial_ranking=wallet_predictions[5],
                    custodial_ranking=wallet_predictions[6],
                    rating_ranking=wallet_predictions[7],
                    security_level_ranking=wallet_predictions[8]
                )
                db.session.add(wallet)

        db.session.commit()

        return redirect(url_for('index'))

    return render_template('ranking.html', form=form)

securewallet/wusers/views.py
import codecs
import hashlib
import uuid
from flask import render_template, url_for, flash, redirect, request, Blueprint, session, Response
from flask_login import login_manager, login_user, current_user, logout_user, login_required
from sqlalchemy import update
from werkzeug.wrappers import Response
from securewallet import db
from securewallet.models import User,Block,TransacForUsere
from securewallet.wusers.forms import RegistrationForm, LoginForm, SecsettingForm, OTPForm, FaceAuthForm
from securewallet.generate_wallet.views import GenerateWalletForm
from securewallet.bc_implementation.forms import GenerateTransactionForm
from securewallet.generate_wallet.wallets import Transaction, InvalidTransactionException, InsufficientFundsException
import pyotp
import base64


users = Blueprint('users', __name__)

@users.route('/signup', methods=['GET', 'POST'])
def signup():
    """User registration route."""
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None:
            flash('Email already exists, Please sign in.', category='error')
            return redirect(url_for('login'))
        user = User(email=form.email.data, password=form.password.data, account_address=form.acc_add,publickey=form.pub_key, privatekey=form.pri_key, auth=0, auth_type=0, bio_desc=None,balance=form.balance)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can Sign in!', category='success')

        session['email'] = user.email
        return redirect(url_for('users.login'))

    return render_template('signup.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        # if user is logged in we get out of here
        return redirect(url_for('core.index'))
    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data) :
            flash('Invalid email, password.', category='error')
            return redirect(url_for('users.login'))

        if user.auth_type == 0:
            login_user(user)
            flash('Logged in successfully.', category='success')
            return redirect(url_for('core.index'))

        elif user.auth_type == 1:
            return redirect(url_for('users.otp', email=form.email.data))
        elif user.auth_type == 2:
            bio_desc = user.bio_desc
            return redirect(url_for('users.face_auth', email=form.email.data, bio_desc=bio_desc))
        elif user.auth_type == 3:
            return redirect(url_for('users.otp', email=form.email.data))
        else:
            # bypass
            login_user(user)
            flash('Logged in successfully.', category='success')
            return redirect(url_for('core.index'))

    return render_template('login.html', form=form)

@users.route('/face_auth', methods=['GET', 'POST'])
def face_auth():
    if 'email' in request.args:
        email = request.args['email']
    else:
        return redirect(url_for('core.index'))

    form = FaceAuthForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=email).first()

        login_user(user)
        flash('Logged in successfully.', category='success')
        return redirect(url_for('core.index'))

    return render_template('face_auth.html', form=form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    session.pop("email",None)
    session.clear() #new if did not work delete it
    flash("Logout success", "success")
    return redirect(url_for('core.index'))


@users.route("/useraccount", methods=['GET'])
@login_required
def useraccount():
    form = GenerateWalletForm()

    current_user_email = str(current_user)
    user = User.query.filter_by(email=current_user_email).first()
    acc_add,pub_key,pri_key  =user.get_keys()
    balance = user.get_balance()

    form.email.data = current_user_email
    form.account_address.data = acc_add
    form.publickey.data = pub_key
    form.privatekey.data = '*'
    form.balance.data=balance

    return render_template('useraccount.html', form=form)


@users.route('/useraccount', methods=['POST'])
@login_required
def download_credentials():
    current_user_email = str(current_user)
    user = User.query.filter_by(email=current_user_email).first()

    if user.auth != 1:
        acc_add, pub_key,pri_key = user.get_keys()

        csv = 'Email Address,Account Address,Public Key,Private Key' + '\n' + current_user_email + ',' + acc_add + ',' + pub_key + ',' + pri_key

        user.privatekey = '*'
        user.auth = 1
        db.session.commit()

        return Response(
            csv,
            mimetype='text/csv',
            headers={'Content-disposition': 'attachment; filename=' + current_user_email + '_credentials.csv'})

    else:
        return 'Error: You have already downloaded your account credentials.'


@users.route('/otp', methods=['GET', 'POST'])
def otp():
    if 'email' in request.args:
        email = request.args['email']
    else:
        return redirect(url_for('core.index'))
    form = OTPForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=email).first()
        account_add = user.account_address
        user_account = codecs.decode(account_add[2:], 'hex')
        otp_token_hex = user_account.hex()
        otp_token = base64.b32encode(bytes.fromhex(otp_token_hex)).decode()
        totp = pyotp.TOTP(otp_token)
        if totp.verify(form.otp.data):
            if user.auth_type == 1:
                login_user(user)
                flash('Logged in successfully.', category='success')
                return redirect(url_for('core.index'))
            elif user.auth_type == 3:
                bio_desc = user.bio_desc
                return redirect(url_for('users.face_auth', email=email, bio_desc=bio_desc))
        else:
            flash('Invalid token.', category='error'),print("form.otp.data",form.otp.data)
            return render_template('otp.html', form=form)
    return render_template('otp.html', form=form)

@users.route("/secsetting", methods=['GET'])
@login_required
def secsetting():
    form = SecsettingForm()
    current_user_email = str(current_user)
    user = User.query.filter_by(email=current_user_email).first()
    account_add = user.account_address
    user_account = codecs.decode(account_add[2:], 'hex')
    otp_token_hex = user_account.hex()
    otp_token = base64.b32encode(bytes.fromhex(otp_token_hex)).decode()
    totp_url = pyotp.TOTP(otp_token).provisioning_uri(name=current_user_email, issuer_name="SecureWallet")
    auth_type = user.auth_type
    form.auth_type.data = auth_type
    form.otp_url.data = totp_url
    return render_template('secsetting.html' , form=form)
######
@users.route('/secsetting', methods=['POST'])
@login_required
def save_secsetting():
    current_user_email = str(current_user)
    user = User.query.filter_by(email=current_user_email).first()

    form = SecsettingForm()

    if form.validate_on_submit():
        bio_desc = form.bio_desc.data

        print('auth_type_radio', form.auth_type_radio.data)
        print('auth_type', form.auth_type.data)
        print('otp_url', form.otp_url.data)
        print('bio_desc', bio_desc)

        auth_type_result = form.auth_type_radio.data

        if auth_type_result == '0' or auth_type_result == '1' or auth_type_result == '2' or auth_type_result == '3':
            user.auth_type = int(auth_type_result)
            user.bio_desc = bio_desc
            db.session.commit()

            return 'Success: Your account security setting has been updated.'
        else:
            return 'Error: Wrong parameters.'


@users.route('/generate_transaction', methods=['GET', 'POST'])
@login_required
def generate_transaction():
    form = GenerateTransactionForm()
    if form.validate_on_submit():
        transaction = create_transaction(form)
        if transaction:
            if perform_transaction(transaction):
                flash('Transaction created successfully', category= 'success')
                return redirect(url_for('users.success'))
        else:
            flash('Error: Invalid Transaction!.', category= 'error')
            redirect(url_for('users.generate_transaction'))
    return render_template('generate_transaction.html', form=form)

@login_required
def create_transaction(form):

    sender_address = form.sender_address.data
    sender_private_key = form.sender_private_key.data.encode('ascii')
    balance = current_user.get_balance()
    recipient_address = form.recipient_address.data
    value = float(form.value.data)
    if sender_address != current_user.account_address:
        flash('Invalid Address:Please enter your correct address.',category= 'error')
    if User.get_balance_by_address(recipient_address) is None:
        flash("Recipient does not exist.", category='error')
    else:
        recipient_balance = User.get_balance_by_address(recipient_address)
        transaction = Transaction(sender_address, sender_private_key, recipient_address, value, balance,recipient_balance)
        return transaction

@login_required
def perform_transaction(transaction):
    if isinstance(transaction, Transaction) and transaction.transfer() and transaction.get_signature():
        user_email = current_user.email
        trans_id = uuid.uuid4().hex
        transaction_id = hashlib.sha256(trans_id.encode()).hexdigest()[:10]
        query = update(User).where(User.email == user_email).values(balance=transaction.balance)
        db.session.execute(query)

securewallet/templates/add_node.html
{% extends "base.html" %}

{% block content %}

<form method="POST" class=" text-center ">
	{# This hidden_tag is a CSRF security feature. #} {{ form.hidden_tag() }}
	<br>
	<br>
	<br>

	<div class="card-body">
		<h4 class="card-title">Add Blockchain nodes</h4>
		<p class="card-text">Enter a list of Blockchain node URLs separated by comma and click on "Add" button to add them to the list of nodes</p>
	</div>

	<div class="form-group col-md-3 my-4">
		{{ form.nodes_url.label (class="form-control-label") }}
		{% if form.nodes_url.errors %}
		{{ form.nodes_url(placeholder='Node URLs', class="form-control is-invalid") }}
		<div class="invalid-feedback">
			{% for error in form.nodes_url.errors %}
			<span>{{ error }}</span>
			{% endfor %}
		</div>
		{% else %}
		{{ form.nodes_url(placeholder='Node URLs', class="form-control") }}
		{% endif %}
	</div>

	<div class="form-group col-md-3 my-4">
		{{ form.submit(class="btn1 btn-md btn-block") }}
	</div>


</form>>


{% endblock %}

securewallet/templates/base.html
<!DOCTYPE html>

<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
	<!-- <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script> -->
	<script src="../static/face-api.min.js"></script>
	<title>base</title>

  </head>

  <body>
<div class="container-fluid">
	<nav class=" navbar-inverse navbar-dark bg-dark ">
		<li class="nav-item">
			<a class=" nav-link navbar-brand"  href="{{url_for('core.index')}}">Secure Wallet</a></li>
		<ul class='nav nav-tabs nav-justified p-4 bg-light '>

			{% if current_user.is_authenticated %}
			<li class="nav-item "><a class="nav-link text-dark"  href="{{ url_for('users.useraccount') }}"> <h6>Wallet Information</h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{ url_for('users.generate_transaction') }}"> <h6> Generate Transactions </h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{ url_for('users.secsetting') }}"> <h6> Security Setting </h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{ url_for('users.get_user_transactions') }}"> <h6> Confirmed transactions </h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{ url_for('users.logout') }}"> <h6> Log Out </h6> </a></li>

			{% else %}
			<li class="nav-item "><a class="nav-link text-dark"  href="{{url_for('bc_implementation.main_blockchain')}}"> <h6> Main Blockchain</h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{url_for('core.ranking')}}"> <h6> Ranking </h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{ url_for('users.login') }}"> <h6> Log In  </h6> </a></li>
			<li class="nav-item"><a class="nav-link text-dark"  href="{{ url_for('users.signup') }}"><h6> Register </h6> </a></li>
			{% endif %}
		</ul>
	</nav>
</div>
{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
		{% for category, message in messages %} {% if category =='error' %}
	<div class="alert alert-danger alter-dismissable fade show" role="alert">
	{{ message }}
	<button type="button" class="close" data-dismiss="alert">
		<span aria-hidden="true">&times;</span>
	</button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
	{{ message }}
	<button type="button" class="close" data-dismiss="alert">
		<span aria-hidden="true">&times;</span>
	</button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}


<div class="container">

	{% block content %}
	{% endblock %}

</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

</html>

securewallet/templates/create_wallet.html
{% extends 'base.html' %}
{% block content %}

<form method="GET">
{{ form.hidden_tag() }}

	<div class="form-group col-md-3 mx-auto">
		<div class="card-body">
			<h4 class="card-title">Wallet Generator</h4>
			<p class="card-text">Click on the button below to generate your blockchain wallet</p>
			{{ form.submit(class="btn1 btn-md btn-block") }}
		</div>
	</div>
	<br>

	<div class="form-group col-md-3 mx-auto">

		{{ form.account_address.label }} {{ form.account_address( class="form-control") }}
	</div>
	<br>

	<div class="form-group col-md-3 mx-auto">

		{{ form.publickey.label }} {{ form.publickey( class="form-control") }}

	</div>
	<br>
	<div class="form-group col-md-3 mx-auto">

		{{ form.privatekey.label }} {{ form.privatekey( class="form-control") }}

	</div>


	<div class="form-group col-md-1 mx-auto">

		{{ form.balance.label }} {{ form.balance( class="form-control") }}

	</div>

	</div>
</form>
{% endblock %}

securewallet/templates/face_auth.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <section class="Form my-4 mx-5">
        <div class="row no-gutters form-control">
            <div class="col-lg-5">
                <div class="img-fluid text-center md-3">
                    <img src="/static/wallbc.jpg" alt="" width="216" height="206">
                </div>
            </div>
            <div class="row-cols-md-3 text-center">
                <br>
                <br>

                <h4> Additional Verification </h4>

                <br>
                <form method="POST">
                    {# This hidden_tag is a CSRF security feature. #}
                    {{ form.hidden_tag() }}

                    <div class="form-group  text-center md-3 mx-auto"><br>
                        {{ form.password.label (class="form-control-label") }}
                        {% if form.password.errors %}
                        {{ form.password(placeholder='Password', class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        <!-- {{ form.password(placeholder='Password', class="form-control") }}<br> -->

                        <video onloadedmetadata="onPlay(this)" id="inputVideo" autoplay muted playsinline style="margin-top: 20px; width: 100%; border: 1px solid black;"></video>
                        <!-- <canvas id="canvas" width="640" height="480"></canvas> -->

                        <div style="display: flex; flex-direction: row; margin: 20px;">
                            <label for="face_auth_result">Face Recognition Result:</label>
                            <label id="face_auth_result" style="font-weight: bold; color: red;">N/A</label>
                        </div>
                    
                    
                        {% endif %}
                    </div>

                    <div class="form-group text-center md-3 mx-auto" id="submit_group" style="margin: 20px;">
                        {{ form.submit(class="btn1 my-3") }}
                    </div>
                </form>
            </div>

        </div>

    </section>
</div>

<script>
    let baseDescriptor = ''
    let inputDescriptor = ''
    let matched = false
    let model = ''

    async function onPlay() {
      const videoEl = $('#inputVideo').get(0)
    //   const canvas = document.getElementById('canvas');
    //   const context = canvas.getContext('2d');

      setInterval(() => {
        // context.drawImage(videoEl, 0, 0, canvas.width, canvas.height);
        // imageData = context.getImageData(0, 0, canvas.width, canvas.height);

        // console.log(imageData)

        this.getDescriptor(videoEl)
      }, 1000);
    }

    function getFaceDetectorOptions() {
        return selectedFaceDetector === SSD_MOBILENETV1
            ? new faceapi.SsdMobilenetv1Options({ minConfidence })
            : new faceapi.TinyFaceDetectorOptions({ inputSize, scoreThreshold })
    }

    async function getDescriptor(input) {
        // descriptor = await faceapi.computeFaceDescriptor(input)
        result = await faceapi
        .detectAllFaces(input, model)
        .withFaceLandmarks()
        .withFaceDescriptors()

        if (!matched) {
            if (result.length) {
                inputDescriptor = result[0]['descriptor']

                console.log(result[0])

                const distance = faceapi.utils.round(
                    faceapi.euclideanDistance(baseDescriptor, inputDescriptor)
                )

                if (distance <= 0.6) {
                    matched = true
                    $('#face_auth_result').text("Passed");
                    $('#face_auth_result').css('color', 'green');
                    $('#submit').disabled = false;
                    $('#submit_group').show();
                } else {
                    matched = false
                    $('#face_auth_result').text("Failed");
                    $('#face_auth_result').css('color', 'red');
                    $('#submit').disabled = true;
                    $('#submit_group').hide();
                }

                console.log(distance, matched)
            } else {
                matched = false
                $('#face_auth_result').text("N/A");
                $('#face_auth_result').css('color', 'red');
                $('#submit').disabled = true;
                $('#submit_group').hide();
            }
        }
    }

    async function run() {
        await faceapi.loadFaceLandmarkModel('/static/weights')
        await faceapi.loadFaceRecognitionModel('/static/weights')

        model = await faceapi.nets.ssdMobilenetv1.load('/static/weights')

        // getBaseDescriptor()

        const stream = await navigator.mediaDevices.getUserMedia({ video: {} })
        const videoEl = $('#inputVideo').get(0)
        videoEl.srcObject = stream
    }

    async function getBaseDescriptor() {
        input = await faceapi.fetchImage('static/photo.jpg')
        descriptor = await faceapi.computeFaceDescriptor(input)

        descriptorJSON = JSON.stringify(descriptor)

        console.log('*****', new Float32Array(Object.values(JSON.parse(descriptorJSON))))

        baseDescriptor = descriptor
    }

    $(document).ready(function() {
        $('#submit').disabled = true;
        $('#submit_group').hide();
        run()

        base_desc_str = new URLSearchParams(window.location.search.substr(1)).get("bio_desc");
        baseDescriptor = Float32Array.from(base_desc_str.split(","), parseFloat)
        // console.log(baseDescriptor)
    })	

</script>

{% endblock %}

securewallet/templates/get_user_transactions.html
{% extends "base.html" %}
{% block content %}

<div class="container">
	<h4 class="card-title text-center pt-5 ">Confirmed Transactions</h4>

	<br>
	<br>

	<table class="table table-striped text-center pt-5">
		<thead>
		<tr>
			<th>Transaction ID</th>
			<th>Date</th>
			<th>Sender Address</th>
			<th>Recipient Address</th>
			<th>Value</th>
		</tr>
		</thead>
		<tbody>

		{% for trans in user_trans %}
		<tr>
			<td>{{trans.transaction_id }}</td>
			<td>{{ trans.date }}</td>
			<td>{{ trans.sender_address }}</td>
			<td>{{ trans.recipient_address}}</td>
			<td>{{ trans.value}}</td>
		</tr>
		{% endfor %}

		</tbody>
	</table>
</div>
{% endblock %}

securewallet/templates/mine_transactions.html
{% extends 'base.html' %}
{% block content %}
 <div class="container-fluid">
	<nav class=" navbar-inverse bg-dark">
		<ul class='nav'>
			<li class="nav-item">
				<a class=" nav-link navbar-brand"  href="{{url_for('bc_implementation.main_blockchain')}}">Main Blockchain</a></li>

			<li class="nav-item"><a class="nav-link"  href="{{url_for('bc_implementation.add_nodes')}}">Add Nodes</a></li>
			<li class="nav-item"><a class="nav-link"  href="{{url_for('bc_implementation.mine_transactions')}}">Mine Transactions</a></li>

		</ul>
	</nav>
 </div>

<div class="container-fluid">
	<h1> Mine Transactions </h1>
	<form method="POST">
		{# This hidden_tag is a CSRF security feature. #}
		{{ form.hidden_tag() }}
		<table class="table table-sm table-hover">
			<thead class="thead-light">
			<tr>
				<th scope="col">Block Index</th>
				<th scope="col">Date</th>
				<th scope="col">Transactions</th>
				<th scope="col">Nonce</th>
				<th scope="col">Previous Hash</th>
			</tr>
			</thead>
			<tbody>
			{% for subfield in form.blockform %}
			<tr>
				<td> {{ form.block.block_index.label (class="form-control-label") }}</td>
				<td> {{ form.block.date.strife('%-I:%M').label (class="form-control-label")  }}</td>
				<td> {{ form.block.transactions.label (class="form-control-label")  }}</td>
				<td> {{ form.block.nonce.label (class="form-control-label")  }}</td>
				<td> {{ form.block.previous_hash.label (class="form-control-label") }} </td>
			</tr>
			{% endfor %}
			</tbody>
		</table>

		<div class="form-group col-md-3 my-4">
			{{ form.submit(class="btn1 btn-md btn-block") }}
		</div>
	</form>
</div>

{% endblock %}